[[Shutdown]]
=== Shutdown

*TODO this section was copied from the AMv3 spec with only minor changes (mostly markup)*

Perform an emergency shutdown on the slivers in the given slice at this aggregate. Resources should be taken offline, such that experimenter access (on both the control and data plane) is cut off. No further actions on the slivers in the given slice should be possible at this aggregate, until an un-specified operator action restores the slice's slivers (or deletes them). This operation is intended for operator use. The slivers are shut down but remain available for further forensics.

.Call Syntax
[source]
----------------
Shutdown(string slice_urn, struct credentials[], struct options)
----------------

This operation is similar to ProtoGENI's  Shutdown operation. The  SFA specification does not include this operation.

No options are required.

Return: On success, the value field of the return struct will contain: XML-RPC boolean, indicating whether the resources associated with this reservation were successfully shut down to a state suitable for forensics. Return should be true, or else an error should be returned.

If the given slice has no resources locally, or was previously Shutdown, return shall be true, indicating the slice is shut down.

See the Common Concepts page for details on the credentials argument. 

This operation is for operator use, to stop a misbehaving resource. Once shut down, the slivers are not available for experimenter use. The underlying resources may be returned to the pool of available resources, depending on resource type and aggregate implementation.

This method returns true (1), unless the resources remain running in the slice after this operation. 

==== Return Codes and Errors

The +Shutdown+ call can return the usual error codes: BADARGS, ERROR, SERVERERROR and UNAVAILABLE. See <<ErrorCodes,Error Codes>> for general errors.

Additionally, the +Shutdown+ call can return the following error codes:
[horizontal]
FORBIDDEN:: Credential does not grant permission to a slice or sliver specified in the +urns+ argument. Or the slice has been shut down.
EXPIRED:: The slice and/or sliver has already expired.
SEARCHFAILED:: The slice or sliver does not exist at this AM.
BUSY:: Slice or sliver is temporarily locked, try again later
INPROGRESS:: Shutdown already in progress

