[[PerformOperationalAction]]
=== PerformOperationalAction

*TODO this section was copied from the AMv3 spec with only minor changes (mostly markup)*

Perform the named operational action on the named slivers, possibly changing the geni_operational_status of the named slivers. E.G. 'start' a VM. For valid operations and expected states, consult the state diagram advertised in the aggregate's advertisement RSpec.

.Call Syntax
[source]
----------------
PerformOperationalAction (string urns[], struct credentials[], string action, 
                          struct options={})
----------------

This operation is similar to ProtoGENI functions like StartSliver, StopSliver, and RestartSliver in the  PG CMv2 API.

Aggregate Managers SHOULD return an error code of 13 (UNSUPPORTED) if they do not support a given action for a given resource. An AM SHOULD constrain actions based on the current operational state of the resource. This is a fast synchronous operation, and MAY start long-running sliver transitions whose status can be queried using Status. This method should only be called, and is only valid, when the sliver is fully allocated (operational status is not geni_pending_allocation).

While the action argument may be aggregate and sliver type specific (none are required for all aggregates and sliver types), this API does define three common actions that AMs should support if possible: geni_start, geni_stop, and geni_restart. Calling PerformOperationalAction with the action geni_start corresponds to the final part of what CreateSliver did in AM API v2. For more information, see the Common Concepts page section on operational actions.

Options include: geni_best_effort. Default is false (action applies to all slivers equally or none; the method returns an error code without changing the operational state if any sliver fails).

Return: On success, the value field of the return struct will contain a list of structs:

[ {
        geni_sliver_urn : <string>,
        geni_allocation_status: <string, eg geni_provisioned>,
        geni_operational_status : <string>,
        geni_expires: <dateTime.rfc3339 of individual sliver expiration>,
        [optional: 'geni_resource_status' : string with resource-specific status in more detail than operational_status; may be omitted],
        [optional: 'geni_error': string explanation of operation failure for this sliver. The field may be omitted but if present may not be null/None.]
        }, 
        ... 
]
;

Note that PerformOperationalAction may return an empty list, if no slivers were in the request or in the specified slice. However, the method may instead return an error (e.g. SEARCHFAILED). Calling this method on a specific sliver that is unknown, expired, or deleted shall result in an error (SEARCHFAILED or EXPIRED or ERROR), unless geni_best_effort is true.

The optional geni_resource_status field MAY be returned for each sliver which contains a resource-specific status that may be more nuanced than the options for geni_operational_status.

See the Common Concepts page for details on allocation and operational states, operational methods, operations on individual slivers, geni_best_effort, sliver expiration times, urns, and credentials. 
