[[Allocate]]
=== Allocate

*TODO this section was copied from the AMv3 spec with only minor changes (mostly markup)*

Allocate resources as described in a request RSpec argument to a slice with the named URN. On success, one or more slivers are allocated, containing resources satisfying the request, and assigned to the given slice. This method returns a listing and description of the resources reserved for the slice by this operation, in the form of a manifest RSpec. Allocated slivers are held for an aggregate-determined period. Clients must <<Renew>> or <<Provision>> slivers before the expiration time (given in the return struct), or the aggregate will automatically <<Delete>> them. Aggregates should implement Allocate() as quick, cheap, and not impacting provisioned resources, such that it can be readily undone. Allocate is an all or nothing request: if the aggregate cannot completely satisfy the request RSpec, it should fail the request entirely.

At some aggregates, experimenter tools may call Allocate multiple times, to add resources to the existing reservation for the same slice. Other aggregates may limit such requests or forbid them entirely. see +:allocate+ in <<GetVersion>>.

.Call Syntax
[source]
----------------
Allocate(string slice_urn,
         struct credentials[],
         geni.rspec rspec,
         struct options)
----------------

NOTE: This is the first part of what CreateSliver used to do in previous versions of the AM API. The second part is now done by <<Provision>>, and the final part is done by <<PerformOperationalAction>>. See *TODO link?* for an overview of this process.

This operation is similar to ProtoGENI's  GetTicket operation.

As described here, the :allocate return from <<GetVersion>> advertises when a client may legally call Allocate (only once at a time per slice, whenever desired, or multiple times only if the requested resources do not interact).

==== Argument 1: +slice_urn+

***********************************
[horizontal]
Supported by the server:: Mandatory
Included by client:: Mandatory
XML-RPC type::  +string+
String content type::  URN
***********************************

The URN of the slice to which the resources specified in rspec will be allocated. For details on GENI AM API URN identifiers, see the GENI wiki page.

==== Argument 2: +rspec+

***********************************
[horizontal]
Supported by the server:: Mandatory
Included by client:: Mandatory
XML-RPC type::  +string+
String content type::  RSpec
***********************************

An RSpec matching the  GENI standard request RSpec schema containing the resources that the caller is requesting for allocation to the slice specified in slice_urn. These are expected to be consistent with the resources returned by a previous invocation of <<ListResources>>. If this RSpec is in a format not listed as supported by <<GetVersion>>, then the aggregate will return an error of +BADVERSION (4)+.

For more details on RSpecs and RSpec versions, see the link:rspec.html[Rspec Document].

==== Argument 3: +credentials+

The standard authorization argument. See <<CommonArgumentCredentials, the Credentials section>>.

==== Argument 4:  +options+

A struct containing optional arguments, indexed by name. See <<OptionsArgument,General Options Argument Section>>.

==== Option: +:end_time+

See the <<CommonOptionEndTime, +:end_time+>> for details.

==== Return Value 

***********************************
[horizontal]
XML-RPC type:: +struct+
***********************************

See the <<CommonReturnSliverInfoList, sliver info list return>> for details.

On success, the value field of the return struct will contain a struct:
***********************************
[horizontal]
XML-RPC type::
[source]
    {
     ":rspec" : <string: geni.rspec manifest of newly allocated slivers>,
     ":slivers" : [
            {
                      :sliver_urn: <string: sliver urn>
                      :expires: <string: dateTime.rfc3339 allocation expiration string, as in :expires from Status>,
                      :allocation_status: <string: sliver state - e.g. :allocated>
            },
            ...
        ]
    }
***********************************

The manifest is a manifest RSpec of only newly allocated slivers, using the schema matching the input request schema (as required on the Common Concepts page).


==== Return Codes and Errors

The +Allocate+ call can return the usual error codes: BADARGS, ERROR, SERVERERROR and UNAVAILABLE. See <<ErrorCodes,Error Codes>> for general errors.

Additionally, the +Allocate+ call can return the following error codes:
[horizontal]
FORBIDDEN:: Credential does not grant permission to a slice specified in the slice URN argument. Or the slice does not have permission to allocate resources at this slice. Or the slice has been shut down.
BADVERSION:: Bad Version of RSpec provided in the rspec argument.
TOOBIG:: Request is too big to be satisfied.
UNSUPPORTED:: The aggregate does not permit multiple allocations to the same slice of this form. See the +:single_allocation+ options of <<GetVersion>> for more information.

