[[Describe]]
=== Describe

*TODO this section was copied from the AMv3 spec with only minor changes (mostly markup)*

 Retrieve a manifest RSpec describing the resources contained by the named entities, e.g. a single slice or a set of the slivers in a slice. This listing and description should be sufficiently descriptive to allow experimenters to use the resources.

Describe is used to list the resources belonging to a particular reservation. The return is the standard AM API struct, with a value that is a struct that always includes a single manifest RSpec, describing the resources in the set of slivers whose URNs were supplied, or describing the entire single slice whose URN was supplied as an argument.

The manifest RSpec should contain all necessary details about resource identity, configuration, and access information necessary for experimenters to use the resources. As that configuration information may change as the resource becomes operationally +:ready+, this information may change. Otherwise, the manifest is mostly static.

Additionally, Describe returns basic state and expiration information for all queried slivers. Valid values for +:allocation_status+ and +:operational_status+ are described on the Common Concepts page.


.Call Syntax
[source]
----------------
Describe(string urns[], struct credentials[], 
         struct rspec_version, struct options[])
----------------


NOTE: This method is part of what ListResources used to do in previous versions of the AM API, and is similar to ProtoGENI  `Resolve`.


==== Argument 1:  +urns+

*TODO*

The :single_allocation return from GetVersion advertises whether or not a client may invoke this method on only some of the slivers in a given :allocation_state in a given slice (default is false - the client may operate on only some of the slivers in a given state).

==== Argument 2:  +credentials+

The standard authorization argument. See <<CommonArgumentCredentials, the Credentials section>>.

For this and other methods that take a slice URN or list of sliver URNs, when using SFA style credentials, this list must include a valid slice credential, granting rights to the caller of the method over the given slice. See the Common Concepts page. 

==== Argument 3: +rspec_version+

***********************************
[horizontal]
Supported by the server:: Mandatory
Included by client:: Mandatory
XmlRpc type:: 
[source]
  struct {
      string type;    # case insensitive
      string version; # case insensitive
  }
***********************************

An XML-RPC struct indicating the type and version of Manifest RSpec to
return. The struct contains 2 members, type and version. type and version are
case-insensitive strings, matching those in +:ad_rspec_versions+ as returned
by +GetVersion+ at this aggregate. Aggregates should return a :code of 4
(BADVERSION) if the requested RSpec version is not one advertised as supported
in +GetVersion+. 

All aggregate managers are required to honor this option. This field is used to specify the format of the returned manifest RSpec.

==== Argument 4:  +options+

A struct containting optional arguments, indexed by name. See <<OptionsArgument,General Options Argument Section>>.

==== Option: +:compressed+

***********************************
[horizontal]
Supported by the server:: Mandatory
Included by client:: Optional
XmlRpc type:: +boolean+
Default: false
***********************************

*TODO*

==== Return

On success, the value field of the return struct will contain a struct:

***********************************
[horizontal]
XmlRpc type::
[source]
{
   ":rspec": <geni.rspec, a Manifest RSpec>
   ":urn": <string slice urn of the containing slice>
   ":slivers": [
               {
                  ":sliver_urn": <string sliver urn>
                  ":expires": <dateTime.rfc3339 allocation expiration string, as in :expires from SliversStatus>,
                  ":allocation_status": <string sliver state - e.g. :allocated or :provisioned >,
                  ":operational_status": <string sliver operational state>,
                  ":error": <optional string. The field may be omitted entirely but may not be null/None, explaining any failure for a sliver.>
               },
               ...
         ]
}
***********************************

Note that the manifest RSpec for allocated slivers may contain less detail than for provisioned slivers. Aggregates are expected to combine the manifests of all requested slivers into a single manifest RSpec. Note that a manifest returned here for only some of the slivers in a slice at this aggregate may contain references to resources not described in this manifest because they are in other slivers.

If a slice urn is supplied and there are no slivers in the given slice at this aggregate, then :rspec shall be a valid manifest RSpec, containing zero (0) node or link elements - that is, specifying no resources. :slivers may be an empty array, or may be an array of previous slivers that have since been deleted or expired. Calling Describe on one or more sliver URNs that are unknown, deleted or expired shall result in an error (e.g. SEARCHFAILED, EXPIRED or ERROR :code).

Manifests are not necessarily static. In general, the manifest of a given sliver should be static once it has reached the operational state :ready (e.g., fully booted). However, this API does not require that to be true.

See the Common Concepts page about the credentials, rspec, and urns arguments, and also for details on allocation states, operational states, and datetime values. See GeniApiIdentifiers for details on URN structure. 


==== Return Codes and Errors

The +Describe+ call can return the usual error codes: BADARGS, ERROR, SERVERERROR and UNAVAILABLE. See <<ErrorCodes,Error Codes>> for general errors.

Additionally, the +Describe+ call can return the following error codes:
[horizontal]
FORBIDDEN:: Credential does not grant permission to a slice or sliver specified in the +urns+ argument. Or the slice has been shut down.
BADVERSION:: Bad Version of manifest RSpec requested with the rspec_version argument.
UNSUPPORTED:: The aggregate does not permit operations on individual slivers in the same slice of this form. *TODO what does this exactly mean? Is this so?* 
EXPIRED:: The slice and/or sliver has expired.
SEARCHFAILED:: The slice or sliver does not exist at this AM.
BUSY:: Slice or sliver is temporarily locked, try again later

